### ISSUE TITLE
auth with Personal Access Token for CLI scripts

### ISSUE THREAD

**Issue by etihwnad** [Asana/python-asana#23] opened 2015-10-02 21:02 UTC
A valid PAT, verified with the suggested:
```
curl -H "Authorization: Bearer ACCESS_TOKEN" https://app.asana.com/api/1.0/users/me
```
an present as an environment variable `ASANA_ACCESS_TOKEN="..."`, used as:
```
client = asana.Client.access_token(os.environ['ASANA_ACCESS_TOKEN'])
```

raises an exception when the library attempts to use Oauth2 to create a session

```
$ python example-create-task.py 
Traceback (most recent call last):
  File "example-create-task.py", line 29, in <module>
    client = asana.Client.access_token(os.environ['ASANA_ACCESS_TOKEN'])
  File "build/bdist.linux-x86_64/egg/asana/client.py", line 224, in access_token
  File "build/bdist.linux-x86_64/egg/asana/session.py", line 11, in __init__
  File "/usr/lib/python2.7/dist-packages/requests_oauthlib/oauth2_session.py", line 65, in __init__
    self.client_id = client_id or client.client_id
AttributeError: 'NoneType' object has no attribute 'client_id'
```

**Comment by noonhub** [comment] 2015-10-14 18:52
@etihwnad can you check what version of the asana package you are using? This feature was introduced in 0.3.0

This is what I get:

     ± |master {1} ✓| → python
    Python 2.7.10 (default, Jul 14 2015, 19:46:27)
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import os
    >>> import asana
    >>> asana.version.VERSION
    '0.3.0'
    >>> client = asana.Client.access_token(os.environ['ASANA_ACCESS_TOKEN'])
    >>> client.users.me()['name']
    u'Wombat'
    >>>

**Comment by noonhub** [comment] 2015-10-20 18:56
Going to close this unless there is reason to believe something in the library is broken.

**Closed by noonhub** 2015-10-20 18:56 UTC

**Comment by yeeland** [comment] 2016-02-09 22:14
I was running into this issue in version 0.5.0. The exception was getting raised in `requests_oauthlib`, which for me was at 0.4.1.

Given that @noonhub appears to be at Uber now, I looked into it a little more in case anyone else runs into this and upgrading `requests_oauthlib` to 0.5.0 or later should do the trick.

**Comment by irmiller22** [comment] 2016-02-24 23:39
I am now running into this issue as well.

Dependencies:
requests==0.9.1
requests_oauthlib==0.5.0

**Comment by theaeolianmachine** [comment] 2016-02-26 18:50
Right now there is intent to upgrade requests_oauthlib to 0.6.1 (See #33) due to another issue - can you test again on requests_oauthlib==0.6.1?

**Comment by irmiller22** [comment] 2016-03-02 15:53
@theaeolianmachine confirmed, that fixed my issue. Thanks!
