### ISSUE TITLE
Adding a custom field to a project raises exception

### ISSUE THREAD

**Issue by cwbusacker** [Asana/python-asana#188] opened 2023-12-14 19:33 UTC
Using Asana Package version 5.0.0 

Trying to add a custom field in the following way:
```
 project_gid = project["gid"]
 api_response = projects_api.add_custom_field_setting_for_project( {"data": {"custom_field": "1201039880834721"}}, project_gid)
```
causes the following exception:
```
  File "/****/create_asana_projects.py", line 106, in command
    api_response = projects_api.add_custom_field_setting_for_project( {"data": {"custom_field": "1201039880834721"}}, project_gid)
  File "/****/lib/python3.10/site-packages/asana/api/projects_api.py", line 55, in add_custom_field_setting_for_project
    (data) = self.add_custom_field_setting_for_project_with_http_info(body, project_gid, **kwargs)  # noqa: E501
  File "/****/lib/python3.10/site-packages/asana/api/projects_api.py", line 144, in add_custom_field_setting_for_project_with_http_info
    (data) = self.api_client.call_api(
  File "/****/lib/python3.10/site-packages/asana/api_client.py", line 336, in call_api
    query_params = [(k, v) for k, v in query_params.items()]
AttributeError: 'list' object has no attribute 'items'
```

Editing the source code in `call_api` appears to fix it, but not sure if that could break it elsewhere.

**Comment by jv-asana** [comment] 2023-12-15 19:54
Hi @cwbusacker,

Thank you for reporting this issue. Because of this we also discovered that we were missing a definition for the `opt_fields` query params the documentation for [Add a custom field to a project](https://developers.asana.com/reference/addcustomfieldsettingforproject) endpoint in our developer docs.

I have gone ahead and sent a fix for this issue you reported under v5.0.2. Thank you for reporting this and helping make our client library better. If you encounter any other issues please don't hesitate to create another GitHub issue.

**Here's break down of the cause:**

1. `add_custom_field_setting_for_project` method [calls the `call_api` method](https://github.com/Asana/python-asana/blob/v5.0.0/asana/api/projects_api.py#L144-L159) with an [empty list of query params](https://github.com/Asana/python-asana/blob/v5.0.0/asana/api/projects_api.py#L104) (NOTE: even though you did not provide query params for this endpoint by default it sends an empty list of query params -> this should be an empty dict)
2. There's a section of code in the [`api_client.py`](https://github.com/Asana/python-asana/blob/v5.0.0/asana/api_client.py) file where `call_api` -> `__call_api` [tries to convert the query param provided from a dict into a list of tuples](https://github.com/Asana/python-asana/blob/v5.0.0/asana/api_client.py#L333-L336). Because the default argument for query params provided was a empty list you run into the `AttributeError: 'list' object has no attribute 'items'` error

**TODO to Fix:**

1. Change default `query_params` in `add_custom_field_setting_for_project` method from list to dict
2. Add a check in `api_client.py` where `call_api` [tries to convert the query param provided from a dict into a list of tuples](https://github.com/Asana/python-asana/blob/v5.0.0/asana/api_client.py#L333-L336) -> check if it is empty before trying to run this code

**Where to perform fix:**

Since the new libraries are auto generated we want to modify the templates that the generator uses to generate the the methods and client
1.  To change the default query params from list to dict we'll need to modify the [`api.mustache`](https://github.com/Asana/python-asana/blob/v5.0.0/codegen/templates/api.mustache#L170) template file (this file is used by the generator to generate all the endpoints under this the [`api` folder](https://github.com/Asana/python-asana/tree/v5.0.0/asana/api))
2. Similarly the client ([`api_client.py`](https://github.com/Asana/python-asana/blob/v5.0.0/asana/api_client.py)) is also auto generated by the generator from the [`api_client.mustache`](https://github.com/Asana/python-asana/blob/v5.0.0/codegen/templates/api_client.mustache) template - [This is where the conversion is being done and where we need to fix](https://github.com/Asana/python-asana/blob/v5.0.0/codegen/templates/api_client.mustache#L340-L343)

**Commits:**
- [Fix: call_api method for when there is empty array of query params](https://github.com/Asana/python-asana/commit/c03c565229f157c17fd91033a6ae14b65aacf048)
- [Fix api.mustache template query params default to array instead of dict](https://github.com/Asana/python-asana/commit/5e045d0a11fc5316b46f8a54c5b9dbd1388f87e9)

**Closed by jv-asana** 2023-12-15 19:54 UTC
